export const PRODUCTS_DATA = [
  {
    id: 1,
    name: 'Chaveirinho Aranha Roxa',
    description: 'Chaveirinho artesanal de crochê com design de aranha em tons roxos vibrantes',
    price: 25.90,
    image: '/hero/hero1.jpg',
    category: 'aranhas',
    badge: 'Popular',
    rating: 5.0,
    inStock: true,
    featured: true,
  },
  {
    id: 2,
    name: 'Chaveirinho Teia Prateada',
    description: 'Delicado chaveirinho com padrão de teia em fios prateados brilhantes',
    price: 22.90,
    image: '/hero/hero2.jpg',
    category: 'teias',
    badge: 'Novo',
    rating: 5.0,
    inStock: true,
    featured: true,
  },
  {
    id: 3,
    name: 'Chaveirinho Aranha Neon',
    description: 'Chaveirinho moderno com detalhes neon que brilham no escuro',
    price: 29.90,
    image: '/hero/hero3.jpg',
    category: 'aranhas',
    badge: 'Exclusivo',
    rating: 5.0,
    inStock: true,
    featured: true,
  },
  {
    id: 4,
    name: 'Chaveirinho Mini Aranha',
    description: 'Versão compacta e fofa da aranha artesanal',
    price: 19.90,
    image: '/hero/hero1.jpg',
    category: 'aranhas',
    badge: 'Best Seller',
    rating: 4.8,
    inStock: true,
    featured: false,
  },
  {
    id: 5,
    name: 'Chaveirinho Teia Dourada',
    description: 'Elegante chaveirinho com fios dourados e acabamento premium',
    price: 32.90,
    image: '/hero/hero2.jpg',
    category: 'teias',
    badge: 'Premium',
    rating: 5.0,
    inStock: true,
    featured: false,
  },
  {
    id: 6,
    name: 'Chaveirinho Aranha Bebê',
    description: 'Adorável aranhinha bebê em crochê com olhinhos fofos',
    price: 24.90,
    image: '/hero/hero3.jpg',
    category: 'aranhas',
    badge: 'Fofo',
    rating: 4.9,
    inStock: true,
    featured: false,
  },
];

export const CATEGORIES = [
  { id: 'all', name: 'Todos', icon: '🕷️' },
  { id: 'aranhas', name: 'Aranhas', icon: '🕷️' },
  { id: 'teias', name: 'Teias', icon: '🕸️' },
];

export const TESTIMONIALS_DATA = [
  {
    id: 1,
    name: 'Maria Silva',
    role: 'Cliente Satisfeita',
    avatar: 'https://i.pravatar.cc/150?img=1',
    rating: 5,
    comment: 'Simplesmente apaixonada pelos chaveirinhos! A qualidade é excepcional e o design é único. Super recomendo!',
  },
  {
    id: 2,
    name: 'João Santos',
    role: 'Colecionador',
    avatar: 'https://i.pravatar.cc/150?img=12',
    rating: 5,
    comment: 'Já comprei vários chaveirinhos e todos são perfeitos. O atendimento é excelente e a entrega rápida.',
  },
  {
    id: 3,
    name: 'Ana Costa',
    role: 'Presenteadora',
    avatar: 'https://i.pravatar.cc/150?img=5',
    rating: 5,
    comment: 'Comprei como presente e foi um sucesso! Todo mundo adorou. Artesanato de primeira qualidade.',
  },
];
